platformName: Android
#模拟器
platformVersion: 5.1.1
deviceName: 127.0.0.1:62001
#mx4真机
#platformVersion: 5.1
#udid:
#deviceName: MX4
appname: kaoyan3.1.0.apk
appPackage: com.tal.kaoyan
appActivity: com.tal.kaoyan.ui.activity.SplashActivity

noReset: False
unicodeKeyboard: True
resetKeyboard: True
ip: 127.0.0.1
port: 4723
